#include "labels.h"

const char *const labels_ua [LABEL_END] = {
    [LABEL_SUNDAY]          = "НЕДІЛЯ",
    [LABEL_MONDAY]          = "ПОНЕДІЛОК",
    [LABEL_TUESDAY]         = "ВІВТОРОК",
    [LABEL_WEDNESDAY]       = "СЕРЕДА",
    [LABEL_THURSDAY]        = "ЧЕТВЕР",
    [LABEL_FRIDAY]          = "П'ЯТНИЦЯ",
    [LABEL_SATURDAY]        = "СУБОТА",

    [LABEL_VOLUME]          = "Гучність",
    [LABEL_BASS]            = "Тембр НЧ",
    [LABEL_MIDDLE]          = "Тембр СЧ",
    [LABEL_TREBLE]          = "Тембр ВЧ",
    [LABEL_FRONTREAR]       = "Фронт / тил",
    [LABEL_BALANCE]         = "Баланс",
    [LABEL_CENTER]          = "Центр",
    [LABEL_SUBWOOFER]       = "Сабвуфер",
    [LABEL_PREAMP]          = "Підсилення",

    [LABEL_IN_TUNER]        = "Тюнер",
    [LABEL_IN_PC]           = "Комп'ютер",
    [LABEL_IN_TV]           = "Телевізор",
    [LABEL_IN_BLUETOOTH]    = "Bluetooth",
    [LABEL_IN_DVD]          = "DVD",
    [LABEL_IN_USB]          = "USB",
    [LABEL_IN_MICROPHONE]   = "Мікрофон",
    [LABEL_IN_GUITAR]       = "Гітара",
    [LABEL_IN_TURNTABLES]   = "Вертушки",
    [LABEL_IN_CASSETTE]     = "Касета",
    [LABEL_IN_PROJECTOR]    = "Проектор",
    [LABEL_IN_SATELLITE]    = "Супутник",
    [LABEL_IN_MIXER]        = "Мікшер",
    [LABEL_IN_KARADIO]      = "KaRadio",

    [LABEL_BOOL_OFF]        = "ВИМКН",
    [LABEL_BOOL_ON]         = "УВІМК",

    [LABEL_TUNER_FM_STATION_NAME]   = "Ім'я FM станції",

    [LABEL_TUNER_IC + TUNER_IC_NO] = "Немає",

    [LABEL_TUNER_BAND + TUNER_BAND_FM_US_EUROPE]    = "США/Європа FM",
    [LABEL_TUNER_BAND + TUNER_BAND_FM_JAPAN]        = "Японія FM",
    [LABEL_TUNER_BAND + TUNER_BAND_FM_WORLDWIDE]    = "Світова FM",
    [LABEL_TUNER_BAND + TUNER_BAND_FM_EASTEUROPE]   = "Сх. Європа FM",

    [LABEL_TUNER_STEP + TUNER_STEP_50K]     = "50кГц",
    [LABEL_TUNER_STEP + TUNER_STEP_100K]    = "100кГц",
    [LABEL_TUNER_STEP + TUNER_STEP_200K]    = "200кГц",

    [LABEL_TUNER_DEEMPH + TUNER_DEEMPH_50u] = "50мкс",
    [LABEL_TUNER_DEEMPH + TUNER_DEEMPH_75u] = "75мкс",

    [LABEL_SPECTRUM_MODE + SP_MODE_STEREO]      = "Стерео",
    [LABEL_SPECTRUM_MODE + SP_MODE_MIXED]       = "Суміщення",
    [LABEL_SPECTRUM_MODE + SP_MODE_WATERFALL]   = "Водоспад",

    [LABEL_PAL_MODE + PAL_SNOW]         = "Сніг",
    [LABEL_PAL_MODE + PAL_AQUA]         = "Вода",
    [LABEL_PAL_MODE + PAL_FIRE]         = "Вогонь",

    [LABEL_AUDIO_IC + AUDIO_IC_NO]      = "Немає",

    [LABEL_ALARM_DAY + ALARM_DAY_OFF]       = "Вимкн",
    [LABEL_ALARM_DAY + ALARM_DAY_WEEKDAYS]  = "Будні",
    [LABEL_ALARM_DAY + ALARM_DAY_ALL_DAYS]  = "Усі дні",

    [LABEL_MUTESTBY + MUTESTBY_POS] = "Актив. 1",
    [LABEL_MUTESTBY + MUTESTBY_NEG] = "Актив. 0",

    // NOTE: Keep in sync with MenuIdx in menu.h
    [LABEL_MENU + MENU_NULL]            = "Назад",

    [LABEL_MENU + MENU_SETUP]           = "Налаштування",

    [LABEL_MENU + MENU_SETUP_SYSTEM]    = "Система",
    [LABEL_MENU + MENU_SETUP_AUDIO]     = "Аудіо",
    [LABEL_MENU + MENU_SETUP_TUNER]     = "Тюнер",
    [LABEL_MENU + MENU_SETUP_SPECTRUM]  = "Спектр",
    [LABEL_MENU + MENU_SETUP_DISPLAY]   = "Дисплей",
    [LABEL_MENU + MENU_SETUP_ALARM]     = "Будильник",
    [LABEL_MENU + MENU_SETUP_RC]        = "Пульт",

    [LABEL_MENU + MENU_SYSTEM_LANG]     = "Мова",
    [LABEL_MENU + MENU_SYSTEM_MUTESTBY] = "Mute і Stby",
    [LABEL_MENU + MENU_SYSTEM_I2C_EXT]  = "I2C розширювач",
    [LABEL_MENU + MENU_SYSTEM_ENC_RES]  = "Крок енкодера",
    [LABEL_MENU + MENU_SYSTEM_SIL_TIM]  = "Таймер тиші",
    [LABEL_MENU + MENU_SYSTEM_RTC_CORR] = "Корекція часу",

    [LABEL_MENU + MENU_I2C_EXT_IN_STAT] = "Статус входів",
    [LABEL_MENU + MENU_I2C_EXT_BT]      = "Контроль Bluetooth",

    [LABEL_MENU + MENU_AUDIO_IC]        = "Аудіопроцесор",
    [LABEL_MENU + MENU_AUDIO_IN]        = "Вхід",

    [LABEL_MENU + MENU_TUNER_IC]        = "Чіп тюнера",
    [LABEL_MENU + MENU_TUNER_BAND]      = "Діапазон",
    [LABEL_MENU + MENU_TUNER_STEP]      = "Крок",
    [LABEL_MENU + MENU_TUNER_DEEMPH]    = "Передвикривл.",
    [LABEL_MENU + MENU_TUNER_STA_MODE]  = "Режим станції",
    [LABEL_MENU + MENU_TUNER_FMONO]     = "Форсувати моно",
    [LABEL_MENU + MENU_TUNER_RDS]       = "Увімкнути RDS",
    [LABEL_MENU + MENU_TUNER_BASS]      = "Посилити НЧ",
    [LABEL_MENU + MENU_TUNER_VOLUME]    = "Гучність",

    [LABEL_MENU + MENU_ALARM_HOUR]      = "Година",
    [LABEL_MENU + MENU_ALARM_MINUTE]    = "Хвилина",
    [LABEL_MENU + MENU_ALARM_DAYS]      = "Дні",

    [LABEL_MENU + MENU_SPECTRUM_MODE]   = "Режим екрана",
    [LABEL_MENU + MENU_SPECTRUM_PEAKS]  = "Піковий рівень",
    [LABEL_MENU + MENU_SPECTRUM_GRAD]   = "Градієнт",

    [LABEL_MENU + MENU_DISPLAY_BR_STBY] = "Яскравість STBY",
    [LABEL_MENU + MENU_DISPLAY_BR_WORK] = "Яскравість",
    [LABEL_MENU + MENU_DISPLAY_ROTATE]  = "Повернути",
    [LABEL_MENU + MENU_DISPLAY_DEF]     = "Головний екран",
    [LABEL_MENU + MENU_DISPLAY_PALETTE] = "Палітра",

    // NOTE: Keep in sync with cmd.h define list
    [LABEL_MENU + MENU_RC_STBY_SWITCH]  = "Режим очікування",
    [LABEL_MENU + MENU_RC_MUTE]         = "Тиша",
    [LABEL_MENU + MENU_RC_VOL_UP]       = "Гучність +",
    [LABEL_MENU + MENU_RC_VOL_DOWN]     = "Гучність -",
    [LABEL_MENU + MENU_RC_MENU]         = "Меню",
    [LABEL_MENU + MENU_RC_CHAN_NEXT]    = "Наступний КН",
    [LABEL_MENU + MENU_RC_CHAN_PREV]    = "Попередній КН",
    [LABEL_MENU + MENU_RC_DIG]          = "Цифра",
    [LABEL_MENU + MENU_RC_IN_NEXT]      = "Наступний ВХ",
    [LABEL_MENU + MENU_RC_NAV_OK]       = "ОК",
    [LABEL_MENU + MENU_RC_NAV_BACK]     = "Назад",
    [LABEL_MENU + MENU_RC_NAV_RIGHT]    = "Вправо",
    [LABEL_MENU + MENU_RC_NAV_UP]       = "Вгору",
    [LABEL_MENU + MENU_RC_NAV_LEFT]     = "Вліво",
    [LABEL_MENU + MENU_RC_NAV_DOWN]     = "Вниз",
    [LABEL_MENU + MENU_RC_BASS_UP]      = "НЧ +",
    [LABEL_MENU + MENU_RC_BASS_DOWN]    = "НЧ -",
    [LABEL_MENU + MENU_RC_MIDDLE_UP]    = "СЧ +",
    [LABEL_MENU + MENU_RC_MIDDLE_DOWN]  = "СЧ -",
    [LABEL_MENU + MENU_RC_TREBLE_UP]    = "ВЧ +",
    [LABEL_MENU + MENU_RC_TREBLE_DOWN]  = "ВЧ +",
    [LABEL_MENU + MENU_RC_LOUDNESS]     = "Тонкомпенсація",
    [LABEL_MENU + MENU_RC_SURROUND]     = "Навколиш. звук",
    [LABEL_MENU + MENU_RC_EFFECT_3D]    = "3D-ефект",
    [LABEL_MENU + MENU_RC_TONE_BYPASS]  = "Вимкнути тон",
    [LABEL_MENU + MENU_RC_TIME]         = "Час",
    [LABEL_MENU + MENU_RC_STOP]         = "Стоп",
    [LABEL_MENU + MENU_RC_PLAY_PAUSE]   = "Грати/Пауза",
    [LABEL_MENU + MENU_RC_REW]          = "Крок назад",
    [LABEL_MENU + MENU_RC_FWD]          = "Крок вперед",
    [LABEL_MENU + MENU_RC_TIMER]        = "Таймер",
    [LABEL_MENU + MENU_RC_SP_MODE]      = "Режим спектру",
    [LABEL_MENU + MENU_RC_SCR_DEF]      = "Головний екран",
};
