#!/bin/sh

# Sanity checks
test -f /mpd-uart.py || exit 0

start() {
	printf "Starting mpd-uart: "
	start-stop-daemon -S -q -b -p /mpd-uart.pid -m \
		-x /usr/bin/python /mpd-uart.py -- -s /dev/ttyAMA0 \
		&& echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping mpd-uart: "
	start-stop-daemon -K -q -p /mpd-uart.pid \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
