
/*******************************************************************************
* generated by lcd-image-converter rev.6efd88c from 2018-09-09 11:35:40 +0300
* font
* filename: /home/Share/Dropbox/Fonts/font-terminus-22-dig.xml
* name: font-terminus-22-dig
* family: xos4 Terminus
* size: 28
* style: Bold
* included characters:  -.0123456789: █
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: template-ampcontrol-m32
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: backward
*  inverse: yes
*******************************************************************************/

/*
typedef struct {
    const uint8_t *data;
    uint16_t width;
    uint16_t height;
} tImage;

typedef struct {
    int32_t code;
    const tImage *image;
} tChar;

typedef struct {
    uint16_t length;
    const tChar *chars;
} tFont;
*/

#include <stdint.h>

#include "fonts.h"



#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x20[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage fontterminus22dig_0x20 = { image_data_fontterminus22dig_0x20, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x2d[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage fontterminus22dig_0x2d = { image_data_fontterminus22dig_0x2d, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x2e[6] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ██
    // ██
    // ██
    // ∙∙
    // ∙∙
    0x00, 0x00, 0x00, 0x00, 0x0e, 0x0e
};
static const tImage fontterminus22dig_0x2e = { image_data_fontterminus22dig_0x2e, 2, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x30[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙███
    // ██∙∙∙∙∙████
    // ██∙∙∙∙█████
    // ██∙∙∙███∙██
    // ██∙∙███∙∙██
    // ██∙███∙∙∙██
    // █████∙∙∙∙██
    // ████∙∙∙∙∙██
    // ███∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xf0, 0xf8, 0x1c, 0x0c, 0x0c, 0x0c, 0x0c, 0x8c, 0xdc, 0xf8, 0xf0, 0xff, 0xff, 0x70, 0x38, 0x1c, 0x0e, 0x07, 0x03, 0x01, 0xff, 0xff, 0x03, 0x07, 0x0e, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0e, 0x07, 0x03
};
static const tImage fontterminus22dig_0x30 = { image_data_fontterminus22dig_0x30, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x31[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙████∙∙∙∙
    // ∙∙█████∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙████████∙
    // ∙∙████████∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x20, 0x30, 0x38, 0xfc, 0xfc, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x0c, 0x0f, 0x0f, 0x0c, 0x0c, 0x0c, 0x00
};
static const tImage fontterminus22dig_0x31 = { image_data_fontterminus22dig_0x31, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x32[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙███∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙███∙∙∙∙∙
    // ∙∙███∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙
    // ███∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xf0, 0xf8, 0x1c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x1c, 0xf8, 0xf0, 0x00, 0x00, 0x80, 0xc0, 0xe0, 0x70, 0x38, 0x1c, 0x0e, 0x07, 0x03, 0x0e, 0x0f, 0x0f, 0x0d, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c
};
static const tImage fontterminus22dig_0x32 = { image_data_fontterminus22dig_0x32, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x33[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙███████∙
    // ∙∙∙███████∙
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x30, 0x38, 0x1c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x1c, 0xf8, 0xf0, 0x00, 0x00, 0x00, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x1e, 0xff, 0xf3, 0x03, 0x07, 0x0e, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0e, 0x07, 0x03
};
static const tImage fontterminus22dig_0x33 = { image_data_fontterminus22dig_0x33, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x34[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙████
    // ∙∙∙∙∙∙█████
    // ∙∙∙∙∙███∙██
    // ∙∙∙∙███∙∙██
    // ∙∙∙███∙∙∙██
    // ∙∙███∙∙∙∙██
    // ∙███∙∙∙∙∙██
    // ███∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███████████
    // ███████████
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 0x00, 0x00, 0x80, 0xc0, 0xe0, 0x70, 0x38, 0xfc, 0xfc, 0xf8, 0xfc, 0xce, 0xc7, 0xc3, 0xc1, 0xc0, 0xc0, 0xc0, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x0f
};
static const tImage fontterminus22dig_0x34 = { image_data_fontterminus22dig_0x34, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x35[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // █████████∙∙
    // ██████████∙
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfc, 0xfc, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x07, 0x07, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x0e, 0xfc, 0xf8, 0x03, 0x07, 0x0e, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0e, 0x07, 0x03
};
static const tImage fontterminus22dig_0x35 = { image_data_fontterminus22dig_0x35, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x36[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙████████∙
    // ∙█████████∙
    // ███∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // █████████∙∙
    // ██████████∙
    // ██∙∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xf0, 0xf8, 0x1c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x00, 0xff, 0xff, 0x06, 0x06, 0x06, 0x06, 0x06, 0x06, 0x0e, 0xfc, 0xf8, 0x03, 0x07, 0x0e, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0e, 0x07, 0x03
};
static const tImage fontterminus22dig_0x36 = { image_data_fontterminus22dig_0x36, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x37[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙
    // ∙∙∙∙∙∙∙██∙∙
    // ∙∙∙∙∙∙██∙∙∙
    // ∙∙∙∙∙∙██∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x7c, 0x7c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x8c, 0xfc, 0x7c, 0x00, 0x00, 0x00, 0x00, 0x00, 0xe0, 0xf8, 0x1e, 0x07, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0f, 0x0f, 0x00, 0x00, 0x00, 0x00
};
static const tImage fontterminus22dig_0x37 = { image_data_fontterminus22dig_0x37, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x38[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xf0, 0xf8, 0x1c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x1c, 0xf8, 0xf0, 0xf3, 0xff, 0x1e, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x1e, 0xff, 0xf3, 0x03, 0x07, 0x0e, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0e, 0x07, 0x03
};
static const tImage fontterminus22dig_0x38 = { image_data_fontterminus22dig_0x38, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x39[33] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙∙██
    // ∙██████████
    // ∙∙█████████
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙█████████∙
    // ∙████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xf0, 0xf8, 0x1c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x1c, 0xf8, 0xf0, 0x07, 0x0f, 0x1c, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0xff, 0xff, 0x00, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0c, 0x0e, 0x07, 0x03
};
static const tImage fontterminus22dig_0x39 = { image_data_fontterminus22dig_0x39, 11, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0x3a[6] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ██
    // ██
    // ██
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ██
    // ██
    // ██
    // ∙∙
    // ∙∙
    // ∙∙
    0x80, 0x80, 0x03, 0x03, 0x07, 0x07
};
static const tImage fontterminus22dig_0x3a = { image_data_fontterminus22dig_0x3a, 2, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0xe28088[6] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};
static const tImage fontterminus22dig_0xe28088 = { image_data_fontterminus22dig_0xe28088, 2, 22};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminus22dig_0xe29688[33] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f, 0x3f
};
static const tImage fontterminus22dig_0xe29688 = { image_data_fontterminus22dig_0xe29688, 11, 22};
#endif


static const tChar fontterminus22dig_array[] = {

#if (0x0 == 0x0)
    // character: ' '
    {0x20, &fontterminus22dig_0x20},
#else
    // character: ' ' == ''
    {0x20, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '-'
    {0x2d, &fontterminus22dig_0x2d},
#else
    // character: '-' == ''
    {0x2d, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '.'
    {0x2e, &fontterminus22dig_0x2e},
#else
    // character: '.' == ''
    {0x2e, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '0'
    {0x30, &fontterminus22dig_0x30},
#else
    // character: '0' == ''
    {0x30, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '1'
    {0x31, &fontterminus22dig_0x31},
#else
    // character: '1' == ''
    {0x31, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '2'
    {0x32, &fontterminus22dig_0x32},
#else
    // character: '2' == ''
    {0x32, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '3'
    {0x33, &fontterminus22dig_0x33},
#else
    // character: '3' == ''
    {0x33, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '4'
    {0x34, &fontterminus22dig_0x34},
#else
    // character: '4' == ''
    {0x34, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '5'
    {0x35, &fontterminus22dig_0x35},
#else
    // character: '5' == ''
    {0x35, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '6'
    {0x36, &fontterminus22dig_0x36},
#else
    // character: '6' == ''
    {0x36, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '7'
    {0x37, &fontterminus22dig_0x37},
#else
    // character: '7' == ''
    {0x37, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '8'
    {0x38, &fontterminus22dig_0x38},
#else
    // character: '8' == ''
    {0x38, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '9'
    {0x39, &fontterminus22dig_0x39},
#else
    // character: '9' == ''
    {0x39, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: ':'
    {0x3a, &fontterminus22dig_0x3a},
#else
    // character: ':' == ''
    {0x3a, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: ' '
    {0xe28088, &fontterminus22dig_0xe28088},
#else
    // character: ' ' == ''
    {0xe28088, &fontterminus22dig_0x},
#endif

#if (0x0 == 0x0)
    // character: '█'
    {0xe29688, &fontterminus22dig_0xe29688}
#else
    // character: '█' == ''
    {0xe29688, &fontterminus22dig_0x}
#endif

};


const tFont fontterminus22dig = { 16, fontterminus22dig_array };
