
/*******************************************************************************
* generated by lcd-image-converter rev.6efd88c from 2018-09-09 11:35:40 +0300
* font
* filename: /home/STM32/Projects/ampcontrol-f103/files/fonts/font-terminus-dig-22.xml
* name: font-terminus-dig-22
* family: xos4 Terminus
* size: 28
* style: Bold
* included characters:  -.0123456789: █
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: no
*
* preset name: ampcontrol-f103-rle3
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: yes
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: backward
*  inverse: yes
*******************************************************************************/

/*
typedef struct {
    const uint8_t *data;
    uint16_t width;
    uint16_t height;
    uint16_t size;
    uint8_t rle;
} tImage;

typedef struct {
    int32_t code;
    const tImage *image;
} tChar;

typedef struct {
    uint16_t length;
    const tChar *chars;
} tFont;
*/

#define no  0x00
#define yes 0x01

#include <stdint.h>

#include "../fonts/fonts.h"




#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x20[2] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x21, 0x00
};
static const tImage fontterminusdig22_0x20 = { image_data_fontterminusdig22_0x20, 11, 22, 2, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x2d[6] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x0b, 0x00, 0x0b, 0x0c, 0x0b, 0x00
};
static const tImage fontterminusdig22_0x2d = { image_data_fontterminusdig22_0x2d, 11, 22, 6, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x2e[4] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ██
    // ██
    // ██
    // ∙∙
    // ∙∙
    0x04, 0x00, 0x02, 0x0e
};
static const tImage fontterminusdig22_0x2e = { image_data_fontterminusdig22_0x2e, 2, 22, 4, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x30[31] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙███
    // ██∙∙∙∙∙████
    // ██∙∙∙∙█████
    // ██∙∙∙███∙██
    // ██∙∙███∙∙██
    // ██∙███∙∙∙██
    // █████∙∙∙∙██
    // ████∙∙∙∙∙██
    // ███∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0xf0, 0xf8, 0x1c, 0x04, 0x0c, 0xee, 0x8c, 0xdc, 0xf8, 0xf0, 0xff, 0xff, 0x70, 0x38, 0x1c, 0x0e, 0x07, 0x03, 0x01, 0xff, 0xff, 0x03, 0x07, 0x0e, 0x05, 0x0c, 0xfd, 0x0e, 0x07, 0x03
};
static const tImage fontterminusdig22_0x30 = { image_data_fontterminusdig22_0x30, 11, 22, 31, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x31[22] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙████∙∙∙∙
    // ∙∙█████∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙████████∙
    // ∙∙████████∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xf9, 0x00, 0x00, 0x20, 0x30, 0x38, 0xfc, 0xfc, 0x09, 0x00, 0x02, 0xff, 0x06, 0x00, 0x03, 0x0c, 0x02, 0x0f, 0x03, 0x0c, 0x01, 0x00
};
static const tImage fontterminusdig22_0x31 = { image_data_fontterminusdig22_0x31, 11, 22, 22, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x32[27] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙███∙
    // ∙∙∙∙∙∙███∙∙
    // ∙∙∙∙∙███∙∙∙
    // ∙∙∙∙███∙∙∙∙
    // ∙∙∙███∙∙∙∙∙
    // ∙∙███∙∙∙∙∙∙
    // ∙███∙∙∙∙∙∙∙
    // ███∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0xf0, 0xf8, 0x1c, 0x05, 0x0c, 0xee, 0x1c, 0xf8, 0xf0, 0x00, 0x00, 0x80, 0xc0, 0xe0, 0x70, 0x38, 0x1c, 0x0e, 0x07, 0x03, 0x0e, 0x0f, 0x0f, 0x0d, 0x07, 0x0c
};
static const tImage fontterminusdig22_0x32 = { image_data_fontterminusdig22_0x32, 11, 22, 27, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x33[27] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙███████∙
    // ∙∙∙███████∙
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0x30, 0x38, 0x1c, 0x05, 0x0c, 0xfd, 0x1c, 0xf8, 0xf0, 0x03, 0x00, 0x05, 0x0c, 0xfa, 0x1e, 0xff, 0xf3, 0x03, 0x07, 0x0e, 0x05, 0x0c, 0xfd, 0x0e, 0x07, 0x03
};
static const tImage fontterminusdig22_0x33 = { image_data_fontterminusdig22_0x33, 11, 22, 27, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x34[24] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙████
    // ∙∙∙∙∙∙█████
    // ∙∙∙∙∙███∙██
    // ∙∙∙∙███∙∙██
    // ∙∙∙███∙∙∙██
    // ∙∙███∙∙∙∙██
    // ∙███∙∙∙∙∙██
    // ███∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███████████
    // ███████████
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x04, 0x00, 0xf3, 0x80, 0xc0, 0xe0, 0x70, 0x38, 0xfc, 0xfc, 0xf8, 0xfc, 0xce, 0xc7, 0xc3, 0xc1, 0x03, 0xc0, 0x02, 0xff, 0x09, 0x00, 0x02, 0x0f
};
static const tImage fontterminusdig22_0x34 = { image_data_fontterminusdig22_0x34, 11, 22, 24, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x35[21] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // █████████∙∙
    // ██████████∙
    // ∙∙∙∙∙∙∙∙███
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x02, 0xfc, 0x09, 0x0c, 0x02, 0x07, 0x06, 0x06, 0xfa, 0x0e, 0xfc, 0xf8, 0x03, 0x07, 0x0e, 0x05, 0x0c, 0xfd, 0x0e, 0x07, 0x03
};
static const tImage fontterminusdig22_0x35 = { image_data_fontterminusdig22_0x35, 11, 22, 21, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x36[25] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙████████∙
    // ∙█████████∙
    // ███∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // ██∙∙∙∙∙∙∙∙∙
    // █████████∙∙
    // ██████████∙
    // ██∙∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0xf0, 0xf8, 0x1c, 0x07, 0x0c, 0xfd, 0x00, 0xff, 0xff, 0x06, 0x06, 0xfa, 0x0e, 0xfc, 0xf8, 0x03, 0x07, 0x0e, 0x05, 0x0c, 0xfd, 0x0e, 0x07, 0x03
};
static const tImage fontterminusdig22_0x36 = { image_data_fontterminusdig22_0x36, 11, 22, 25, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x37[22] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ███████████
    // ███████████
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙∙██∙
    // ∙∙∙∙∙∙∙██∙∙
    // ∙∙∙∙∙∙∙██∙∙
    // ∙∙∙∙∙∙██∙∙∙
    // ∙∙∙∙∙∙██∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙██∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x02, 0x7c, 0x06, 0x0c, 0xfd, 0x8c, 0xfc, 0x7c, 0x05, 0x00, 0xfb, 0xe0, 0xf8, 0x1e, 0x07, 0x01, 0x06, 0x00, 0x02, 0x0f, 0x04, 0x00
};
static const tImage fontterminusdig22_0x37 = { image_data_fontterminusdig22_0x37, 11, 22, 22, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x38[28] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙███
    // ∙█████████∙
    // ∙∙███████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0xf0, 0xf8, 0x1c, 0x05, 0x0c, 0xfa, 0x1c, 0xf8, 0xf0, 0xf3, 0xff, 0x1e, 0x05, 0x0c, 0xfa, 0x1e, 0xff, 0xf3, 0x03, 0x07, 0x0e, 0x05, 0x0c, 0xfd, 0x0e, 0x07, 0x03
};
static const tImage fontterminusdig22_0x38 = { image_data_fontterminusdig22_0x38, 11, 22, 28, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x39[25] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙███████∙∙
    // ∙█████████∙
    // ███∙∙∙∙∙███
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ██∙∙∙∙∙∙∙██
    // ███∙∙∙∙∙∙██
    // ∙██████████
    // ∙∙█████████
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙∙██
    // ∙∙∙∙∙∙∙∙███
    // ∙█████████∙
    // ∙████████∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0xf0, 0xf8, 0x1c, 0x05, 0x0c, 0xfa, 0x1c, 0xf8, 0xf0, 0x07, 0x0f, 0x1c, 0x06, 0x18, 0xfd, 0xff, 0xff, 0x00, 0x07, 0x0c, 0xfd, 0x0e, 0x07, 0x03
};
static const tImage fontterminusdig22_0x39 = { image_data_fontterminusdig22_0x39, 11, 22, 25, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0x3a[7] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ██
    // ██
    // ██
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ██
    // ██
    // ██
    // ∙∙
    // ∙∙
    // ∙∙
    0xfa, 0x80, 0x80, 0x03, 0x03, 0x07, 0x07
};
static const tImage fontterminusdig22_0x3a = { image_data_fontterminusdig22_0x3a, 2, 22, 7, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0xe28088[2] = {
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    // ∙∙
    0x06, 0x00
};
static const tImage fontterminusdig22_0xe28088 = { image_data_fontterminusdig22_0xe28088, 2, 22, 2, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_fontterminusdig22_0xe29688[4] = {
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    // ███████████
    0x16, 0xff, 0x0b, 0x3f
};
static const tImage fontterminusdig22_0xe29688 = { image_data_fontterminusdig22_0xe29688, 11, 22, 4, yes};
#endif


static const tChar fontterminusdig22_array[] = {

#if (0x0 == 0x0)
    // character: ' '
    {0x20, &fontterminusdig22_0x20},
#else
    // character: ' ' == ''
    {0x20, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '-'
    {0x2d, &fontterminusdig22_0x2d},
#else
    // character: '-' == ''
    {0x2d, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '.'
    {0x2e, &fontterminusdig22_0x2e},
#else
    // character: '.' == ''
    {0x2e, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '0'
    {0x30, &fontterminusdig22_0x30},
#else
    // character: '0' == ''
    {0x30, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '1'
    {0x31, &fontterminusdig22_0x31},
#else
    // character: '1' == ''
    {0x31, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '2'
    {0x32, &fontterminusdig22_0x32},
#else
    // character: '2' == ''
    {0x32, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '3'
    {0x33, &fontterminusdig22_0x33},
#else
    // character: '3' == ''
    {0x33, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '4'
    {0x34, &fontterminusdig22_0x34},
#else
    // character: '4' == ''
    {0x34, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '5'
    {0x35, &fontterminusdig22_0x35},
#else
    // character: '5' == ''
    {0x35, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '6'
    {0x36, &fontterminusdig22_0x36},
#else
    // character: '6' == ''
    {0x36, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '7'
    {0x37, &fontterminusdig22_0x37},
#else
    // character: '7' == ''
    {0x37, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '8'
    {0x38, &fontterminusdig22_0x38},
#else
    // character: '8' == ''
    {0x38, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '9'
    {0x39, &fontterminusdig22_0x39},
#else
    // character: '9' == ''
    {0x39, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: ':'
    {0x3a, &fontterminusdig22_0x3a},
#else
    // character: ':' == ''
    {0x3a, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: ' '
    {0xe28088, &fontterminusdig22_0xe28088},
#else
    // character: ' ' == ''
    {0xe28088, &fontterminusdig22_0x},
#endif

#if (0x0 == 0x0)
    // character: '█'
    {0xe29688, &fontterminusdig22_0xe29688}
#else
    // character: '█' == ''
    {0xe29688, &fontterminusdig22_0x}
#endif

};


const tFont fontterminusdig22 = { 16, fontterminusdig22_array };
